-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       (SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA ed2
        WHERE YEAR(ed2.DIFFERENTIATION_DATE) = YEAR(ed1.DIFFERENTIATION_DATE)
       ) - ed1.SIZE_OF_COLONY AS YEAR_DEV,
       ID  
FROM ECOLI_DATA ed1
ORDER BY YEAR ASC, YEAR_DEV ASC
         