-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.LENGTH = (SELECT MAX(LENGTH)
                   FROM FISH_INFO FI2
                   WHERE FI2.FISH_TYPE = FI.FISH_TYPE
                   AND LENGTH >= 10)
ORDER BY ID